### ISSUE TITLE
MRI experiments

### ISSUE THREAD

**Issue by xiaoiker** [Entodi/fusion#52]
Hi,
Thanks for your code. But where is the code for MRI tasks? Can you provide a small example of how to run the MRI tasks?

Thanks very much.

**Comment by Entodi** [comment]
Hello Wei Peng, 

The package is under development and not officially fully released yet. Thus I have not created tutorials yet.

The branch feature/Oasis has config available to run and can give your idea how to run with MRI. It has almost the same structure as experiment natural images. However, I can not share OASIS3 dataset, as it is not open source and requires a request on the official website. Thus, I don't have a pure example.

Also, you can write me to my email eidos92@gmail.com if you want to collaborate.

Regards,
Alex

**Comment by xiaoiker** [comment]
Great, I will contact you by email. Many thanks Alex.
